<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-15 07:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Excavator Operator', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Kitwe, Copperbelt', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('-13.000000'), help_text='Latitude: -8.0 to -18.0 (Zambia)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-18.0')), django.core.validators.MaxValueValidator(Decimal('-8.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('28.000000'), help_text='Longitude: 22.0 to 34.0 (Zambia)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('22.0')), django.core.validators.MaxValueValidator(Decimal('34.0'))])),
                ('license_doc', models.FileField(blank=True, help_text='Upload ZEMA or Ministry of Mines license (PDF/Image)', null=True, upload_to='mines/licenses/')),
                ('license_expiry', models.DateField(blank=True, help_text='License expiry date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mine',
                'verbose_name_plural': 'Mines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('last_service', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mining.mine')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='mining.mine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-date', '-logged_at'],
                'unique_together': {('mine', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +260971234567', regex='^\\+?260\\d{9}$')])),
                ('receive_sms', models.BooleanField(default=True)),
                ('nrc', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='NRC format: 123456/78/9', regex='^\\d{6}/\\d{2}/\\d{1}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mining.mine')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='mining.role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['mine', 'name'],
                'unique_together': {('mine', 'nrc')},
            },
        ),
    ]
=======
# Generated by Django 5.2.8 on 2025-11-15 07:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Excavator Operator', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='e.g., Kitwe, Copperbelt', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('-13.000000'), help_text='Latitude: -8.0 to -18.0 (Zambia)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-18.0')), django.core.validators.MaxValueValidator(Decimal('-8.0'))])),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('28.000000'), help_text='Longitude: 22.0 to 34.0 (Zambia)', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('22.0')), django.core.validators.MaxValueValidator(Decimal('34.0'))])),
                ('license_doc', models.FileField(blank=True, help_text='Upload ZEMA or Ministry of Mines license (PDF/Image)', null=True, upload_to='mines/licenses/')),
                ('license_expiry', models.DateField(blank=True, help_text='License expiry date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mine',
                'verbose_name_plural': 'Mines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('last_service', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mining.mine')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='mining.mine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-date', '-logged_at'],
                'unique_together': {('mine', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Format: +260971234567', regex='^\\+?260\\d{9}$')])),
                ('receive_sms', models.BooleanField(default=True)),
                ('nrc', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='NRC format: 123456/78/9', regex='^\\d{6}/\\d{2}/\\d{1}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mining.mine')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='mining.role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['mine', 'name'],
                'unique_together': {('mine', 'nrc')},
            },
        ),
    ]
>>>>>>> ce25d35ba351259f21575ed2014c56965ea97c25
