<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-15 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['mine__name', 'last_name', 'first_name'], 'permissions': [('can_export_napsa', 'Can export NAPSA report'), ('can_view_safety', 'Can view training records'), ('can_manage_shifts', 'Can assign shifts')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., John', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., Mwansa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_safety_training',
            field=models.DateField(blank=True, help_text='ZEMA annual training', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='napsa_number',
            field=models.CharField(blank=True, help_text='NAPSA Registration Number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mine',
            field=models.ForeignKey(help_text='Assigned mine', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mining.mine'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nrc',
            field=models.CharField(help_text='National Registration Card', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='NRC: 123456/78/9', regex='^\\d{6}/\\d{2}/\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='owner',
            field=models.ForeignKey(help_text='System user', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='SMS alerts', max_length=15, validators=[django.core.validators.RegexValidator(message='+260971234567', regex='^\\+260\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='ID photo', null=True, upload_to='employees/photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_sms',
            field=models.BooleanField(default=True, help_text='Shift & safety alerts'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('General Manager', 'General Manager'), ('Mine Manager', 'Mine Manager'), ('Operations Manager', 'Operations Manager'), ('HR Manager', 'HR Manager'), ('Shift Supervisor', 'Shift Supervisor'), ('Section Supervisor', 'Section Supervisor'), ('Safety Supervisor', 'Safety Supervisor'), ('Drill Operator', 'Drill Operator'), ('Blasting Operator', 'Blasting Operator'), ('Loader Operator', 'Loader Operator'), ('Haul Truck Driver', 'Haul Truck Driver'), ('Excavator Operator', 'Excavator Operator'), ('Mechanical Technician', 'Mechanical Technician'), ('Electrical Technician', 'Electrical Technician'), ('Instrumentation Technician', 'Instrumentation Technician'), ('Auto Electrician', 'Auto Electrician'), ('Safety Officer', 'Safety Officer'), ('Environmental Officer', 'Environmental Officer'), ('First Aider', 'First Aider'), ('Storeman', 'Storeman'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Cook', 'Cook')], help_text='ZM mining job role', max_length=50),
        ),
    ]
=======
# Generated by Django 5.2.8 on 2025-11-15 08:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['mine__name', 'last_name', 'first_name'], 'permissions': [('can_export_napsa', 'Can export NAPSA report'), ('can_view_safety', 'Can view training records'), ('can_manage_shifts', 'Can assign shifts')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., John', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., Mwansa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_safety_training',
            field=models.DateField(blank=True, help_text='ZEMA annual training', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='napsa_number',
            field=models.CharField(blank=True, help_text='NAPSA Registration Number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mine',
            field=models.ForeignKey(help_text='Assigned mine', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='mining.mine'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nrc',
            field=models.CharField(help_text='National Registration Card', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='NRC: 123456/78/9', regex='^\\d{6}/\\d{2}/\\d{1}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='owner',
            field=models.ForeignKey(help_text='System user', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='SMS alerts', max_length=15, validators=[django.core.validators.RegexValidator(message='+260971234567', regex='^\\+260\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='ID photo', null=True, upload_to='employees/photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_sms',
            field=models.BooleanField(default=True, help_text='Shift & safety alerts'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('General Manager', 'General Manager'), ('Mine Manager', 'Mine Manager'), ('Operations Manager', 'Operations Manager'), ('HR Manager', 'HR Manager'), ('Shift Supervisor', 'Shift Supervisor'), ('Section Supervisor', 'Section Supervisor'), ('Safety Supervisor', 'Safety Supervisor'), ('Drill Operator', 'Drill Operator'), ('Blasting Operator', 'Blasting Operator'), ('Loader Operator', 'Loader Operator'), ('Haul Truck Driver', 'Haul Truck Driver'), ('Excavator Operator', 'Excavator Operator'), ('Mechanical Technician', 'Mechanical Technician'), ('Electrical Technician', 'Electrical Technician'), ('Instrumentation Technician', 'Instrumentation Technician'), ('Auto Electrician', 'Auto Electrician'), ('Safety Officer', 'Safety Officer'), ('Environmental Officer', 'Environmental Officer'), ('First Aider', 'First Aider'), ('Storeman', 'Storeman'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Cook', 'Cook')], help_text='ZM mining job role', max_length=50),
        ),
    ]
>>>>>>> ce25d35ba351259f21575ed2014c56965ea97c25
