<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('production_trend', 'Production Trend (Line)'), ('mine_share', 'Mine Output Share (Pie)'), ('equipment_status', 'Equipment Status (Bar)'), ('workforce', 'Workforce by Mine (Bar)'), ('monthly_target', 'Monthly Target vs Actual (Combo)')], max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
=======
# Generated by Django 5.2.8 on 2025-11-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('production_trend', 'Production Trend (Line)'), ('mine_share', 'Mine Output Share (Pie)'), ('equipment_status', 'Equipment Status (Bar)'), ('workforce', 'Workforce by Mine (Bar)'), ('monthly_target', 'Monthly Target vs Actual (Combo)')], max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
>>>>>>> ce25d35ba351259f21575ed2014c56965ea97c25
